/* Topic-by-topic CP route informed by IIT Kanpur PClub and SPO materials. */
(function(){
  'use strict';
  const PCLUB='https://pclub.in/roadmap/2024/07/21/cp-roadmap/';
  const CPH='https://cses.fi/book/index.php';
  const CSES='https://cses.fi/problemset/list/';
  const USACO='https://usaco.guide/';
  const CPALGO='https://cp-algorithms.com/';
  const APNA_C='https://www.youtube.com/watch?v=irqbmMNs2Bo';
  const HARRY_C='https://www.youtube.com/watch?v=aZb0iu4uGwA';
  const APNA_DSA='https://www.youtube.com/playlist?list=PLfqMhTWNBTe137I_EPQd34TsgV6IO55pt';
  const HARRY_CPP='https://www.youtube.com/playlist?list=PLu0W_9lII9agpFUAlPFe_VNSlXW5uE0YL';
  const GATEWALLAH='https://www.youtube.com/@gatewallahbypw';
  const stages=[
    {id:'c',label:'01 · CURRENT',title:'Finish your C foundations',time:'Keep pace with college',goal:'Get comfortable turning a small problem into tested code. Keep C as your class language; this is the bridge into CP, not a second syllabus to rush.',topics:[
      {id:'c-branch',name:'Conditions: if / else and switch',notes:[['CodeWithHarry · C notes','https://www.codewithharry.com/notes'],['C language reference','https://en.cppreference.com/w/c/language']],practice:[['HackerRank · Conditional Statements','https://www.hackerrank.com/challenges/conditional-statements-in-c/problem'],['Codeforces 4A · Watermelon','https://codeforces.com/problemset/problem/4/A'],['Codeforces 231A · Team','https://codeforces.com/problemset/problem/231/A']],videoTopic:'C if else conditional statements',featured:[['Apna College · conditional statements','https://www.youtube.com/watch?v=irqbmMNs2Bo&t=7275s']]},
      {id:'c-loops',name:'Loops, tracing and edge cases',notes:[['CodeWithHarry · C notes','https://www.codewithharry.com/notes'],['NPTEL programming courses','https://nptel.ac.in/courses']],practice:[['HackerRank · For Loop in C','https://www.hackerrank.com/challenges/for-loop-in-c/problem'],['Codeforces 50A · Domino piling','https://codeforces.com/problemset/problem/50/A']],videoTopic:'C loops for loop while loop',featured:[['Apna College · loop control','https://www.youtube.com/watch?v=irqbmMNs2Bo&t=9936s']]},
      {id:'c-functions',name:'Functions and recursion',notes:[['CodeWithHarry · C notes','https://www.codewithharry.com/notes'],['Beej’s C guide','https://beej.us/guide/bgc/']],practice:[['HackerRank · C practice','https://www.hackerrank.com/domains/c'],['CSES · introductory problems','https://cses.fi/problemset/list/']],videoTopic:'C functions recursion',featured:[['Apna College · functions and recursion','https://www.youtube.com/watch?v=irqbmMNs2Bo&t=13894s']]},
      {id:'c-arrays',name:'Arrays, strings and pointer basics',notes:[['CodeWithHarry · C notes','https://www.codewithharry.com/notes'],['Beej’s C guide','https://beej.us/guide/bgc/']],practice:[['HackerRank · C practice','https://www.hackerrank.com/domains/c'],['HackerRank · Arrays DS','https://www.hackerrank.com/challenges/arrays-ds/problem']],videoTopic:'C arrays strings pointers',featured:[['Apna College · pointers','https://www.youtube.com/watch?v=irqbmMNs2Bo&t=19290s'],['Apna College · arrays','https://www.youtube.com/watch?v=irqbmMNs2Bo&t=22730s']]}
    ]},
    {id:'cpp',label:'02 · TRANSITION',title:'Move to C++ when C feels steady',time:'1–2 weeks, alongside class',goal:'Competitive programming commonly uses C++ because STL gives you tested containers and algorithms. C and C++ are distinct languages; learn the C++ basics you need instead of trying to master both at once.',topics:[
      {id:'cpp-basics',name:'C++ input/output, vectors, strings and pairs',notes:[['LearnCpp · beginner tutorial','https://www.learncpp.com/'],['C++ reference','https://en.cppreference.com/w/']],practice:[['HackerRank · C++ practice','https://www.hackerrank.com/domains/cpp'],['CSES · Introductory problems','https://cses.fi/problemset/list/']],videoTopic:'C++ basics vector string pair'},
      {id:'cpp-stl',name:'STL: sort, map, set, stack, queue and heap',notes:[['IITK PClub roadmap · STL / intro','https://pclub.in/roadmap/2024/07/21/cp-roadmap/'],['CP-Algorithms reference','https://cp-algorithms.com/']],practice:[['Codeforces · implementation problems','https://codeforces.com/problemset?tags=implementation'],['CSES · Sorting and Searching','https://cses.fi/problemset/list/']],videoTopic:'C++ STL vector sort map set competitive programming'}
    ]},
    {id:'beginner',label:'03 · BEGINNER CP',title:'Build problem-solving habits',time:'4–6 weeks',goal:'Read constraints, choose a simple approach, state its complexity, code it, and test boundary cases. Enter contests early at a comfortable level; you do not need to finish every course first.',topics:[
      {id:'complexity',name:'Implementation, simulation and time complexity',notes:[['IITK PClub · getting started','https://pclub.in/roadmap/2024/07/21/cp-roadmap/'],['USACO Guide · Bronze','https://usaco.guide/bronze/intro-complete']],practice:[['CSES · Weird Algorithm','https://cses.fi/problemset/task/1068/'],['Codeforces · 800-rated set','https://codeforces.com/problemset?tags=800-800'],['HackerRank · Problem Solving','https://www.hackerrank.com/domains/algorithms']],videoTopic:'competitive programming implementation time complexity beginner'},
      {id:'arrays-sort',name:'Arrays, sorting, prefix sums and binary search',notes:[['CP-Algorithms · binary search','https://cp-algorithms.com/num_methods/binary_search.html'],['USACO Guide · Bronze','https://usaco.guide/bronze/intro-complete']],practice:[['CSES · Distinct Numbers','https://cses.fi/problemset/task/1621/'],['CSES · Apartments','https://cses.fi/problemset/task/1084/'],['Codeforces 339A · Helpful Maths','https://codeforces.com/problemset/problem/339/A']],videoTopic:'arrays sorting binary search prefix sums competitive programming'}
    ]},
    {id:'patterns',label:'04 · INTERMEDIATE',title:'Learn reusable patterns',time:'6–10 weeks',goal:'Add one pattern at a time. Keep a mistake log and re-solve problems after reading an editorial instead of measuring progress by video hours.',topics:[
      {id:'two-pointers',name:'Two pointers, sliding windows and bit operations',notes:[['IITK PClub competitive programming roadmap','https://pclub.in/roadmap/2024/07/21/cp-roadmap/'],['CP-Algorithms','https://cp-algorithms.com/']],practice:[['CSES · Playlist','https://cses.fi/problemset/task/1141/'],['Codeforces · Two pointers tag','https://codeforces.com/problemset?tags=two+pointers'],['Codeforces · Bitmasks tag','https://codeforces.com/problemset?tags=bitmasks']],videoTopic:'two pointers sliding window bit manipulation competitive programming'},
      {id:'recursion-greedy',name:'Recursion, complete search and greedy',notes:[['USACO Guide · Bronze','https://usaco.guide/bronze/intro-complete'],['CP-Algorithms · greedy','https://cp-algorithms.com/']],practice:[['CSES · Creating Strings','https://cses.fi/problemset/task/1622/'],['CSES · Movie Festival','https://cses.fi/problemset/task/1629/'],['Codeforces · Greedy tag','https://codeforces.com/problemset?tags=greedy']],videoTopic:'recursion backtracking complete search greedy algorithms competitive programming'}
    ]},
    {id:'core-dsa',label:'05 · CORE DSA',title:'Trees, graphs and dynamic programming',time:'Build over a semester',goal:'Study graph traversal and DP only after arrays, recursion and complexity are comfortable. These topics connect competitive coding to your core CS and future AI work.',topics:[
      {id:'graphs',name:'BFS, DFS, components, DSU and shortest paths',notes:[['CP-Algorithms · graph section','https://cp-algorithms.com/graph/breadth-first-search.html'],['USACO Guide · Silver','https://usaco.guide/silver/']],practice:[['CSES · Counting Rooms','https://cses.fi/problemset/task/1192/'],['CSES · Labyrinth','https://cses.fi/problemset/task/1193/'],['Codeforces · Graphs tag','https://codeforces.com/problemset?tags=graphs']],videoTopic:'BFS DFS graph algorithms DSU shortest path GATE Wallah'},
      {id:'dp',name:'Dynamic programming: state, transition, base cases',notes:[['CP-Algorithms · introduction to DP','https://cp-algorithms.com/dynamic_programming/intro-to-dp.html'],['USACO Guide · DP','https://usaco.guide/gold/intro-dp']],practice:[['AtCoder DP · Frog 1','https://atcoder.jp/contests/dp/tasks/dp_a'],['CSES · Dice Combinations','https://cses.fi/problemset/task/1633/'],['AtCoder DP · Knapsack 1','https://atcoder.jp/contests/dp/tasks/dp_d']],videoTopic:'dynamic programming competitive programming GATE Wallah'}
    ]},
    {id:'advanced',label:'06 · OPTIONAL ADVANCED',title:'Explore advanced topics when ready',time:'After regular contests',goal:'The IITK roadmap goes much further. Treat these as elective branches, not prerequisites for being a capable engineer or entering beginner contests.',topics:[
      {id:'advanced-topics',name:'Hashing, string matching, range queries and tree algorithms',notes:[['IITK PClub · advanced roadmap topics','https://pclub.in/roadmap/2024/07/21/cp-roadmap/'],['CP-Algorithms','https://cp-algorithms.com/'],['Competitive Programmer’s Handbook','https://cses.fi/book/book.pdf']],practice:[['CSES · Range Queries','https://cses.fi/problemset/list/'],['Codeforces · String algorithms','https://codeforces.com/problemset?tags=strings'],['AtCoder · Educational DP','https://atcoder.jp/contests/dp/tasks']],videoTopic:'string hashing range queries segment tree tree algorithms competitive programming'}
    ]}
  ];
  function safe(value){try{const u=new URL(value);return ['https:'].includes(u.protocol)?u.href:'#'}catch(_){return '#'}}
  function esc(s){return String(s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
  function youtube(handle){return 'https://www.youtube.com/@'+handle+'/playlists'}
  function state(){try{return JSON.parse(localStorage.getItem('arise.cpRoadmap.v1')||'{}')}catch(_){return {}}}
  function save(data){localStorage.setItem('arise.cpRoadmap.v1',JSON.stringify(data))}
  function resourceList(items){return items.map(function(x){return '<a href="'+esc(safe(x[1]))+'" target="_blank" rel="noopener">'+esc(x[0])+' ↗</a>'}).join('')}
  function render(){
    const host=document.getElementById('cp-roadmap-grid');if(!host)return;
    const saved=state();let done=0,total=0;
    const openIds=Array.from(host.querySelectorAll('.cp-stage[open]')).map(function(el){return el.dataset.cpStage});
    host.innerHTML=stages.map(function(stage,index){
      const rows=stage.topics.map(function(topic){const checked=!!saved[topic.id];total++;if(checked)done++;const videos=(topic.featured||[]).map(function(v){return '<a href="'+esc(safe(v[1]))+'" target="_blank" rel="noopener">'+esc(v[0])+' ↗</a>'}).join('')+'<a href="'+esc(youtube('ApnaCollegeOfficial',topic.videoTopic))+'" target="_blank" rel="noopener">Apna College · more ↗</a><a href="'+esc(youtube('CodeWithHarry',topic.videoTopic))+'" target="_blank" rel="noopener">CodeWithHarry ↗</a><a href="'+esc(youtube('gatewallah_ee_ec_cs_in',topic.videoTopic))+'" target="_blank" rel="noopener">GATE Wallah ↗</a>';return '<article class="cp-topic-row"><div class="cp-topic-title"><label><input type="checkbox" data-cp-topic="'+esc(topic.id)+'" '+(checked?'checked':'')+'><span>'+esc(topic.name)+'</span></label></div><div class="cp-topic-resources"><div><small>LECTURES · FOCUSED PICKS + CHANNELS</small><div class="cp-resource-links">'+videos+'</div></div><div><small>NOTES · EXPLANATIONS</small><div class="cp-resource-links">'+resourceList(topic.notes)+'</div></div><div><small>PROBLEMS · PRACTICE</small><div class="cp-resource-links">'+resourceList(topic.practice)+'</div></div></div></article>'}).join('');
      const stageDone=stage.topics.filter(function(topic){return !!saved[topic.id]}).length;
      const isOpen=openIds.length?openIds.includes(stage.id):index===0;
      return '<details class="cp-stage" data-cp-stage="'+esc(stage.id)+'" '+(isOpen?'open':'')+'><summary><span class="cp-stage-label">'+esc(stage.label)+'</span><span class="cp-stage-heading"><b>'+esc(stage.title)+'</b><small>'+esc(stage.time)+' · '+stageDone+'/'+stage.topics.length+' topics checked</small></span><span class="cp-stage-chevron">⌄</span></summary><div class="cp-stage-body"><p>'+esc(stage.goal)+'</p>'+rows+'</div></details>'
    }).join('');
    const label=document.getElementById('cp-route-progress-label');if(label)label.textContent=done+' / '+total+' topic milestones';
    const bar=document.getElementById('cp-route-progress-bar');if(bar)bar.style.width=(total?Math.round(done/total*100):0)+'%';
  }
  document.addEventListener('change',function(event){const input=event.target.closest('[data-cp-topic]');if(!input)return;const saved=state();saved[input.dataset.cpTopic]=input.checked;save(saved);render()});
  document.addEventListener('click',function(event){if(!event.target.closest('[data-cp-reset]'))return;if(!window.confirm('Reset only the CP roadmap checkmarks saved on this device?'))return;localStorage.removeItem('arise.cpRoadmap.v1');render()});
  render();
})();
