/* Curated learning paths and original publisher links. Update links/official calendars each semester. */
window.ORBIT_DATA = (function(){
  const mit='https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2020/';
  const mitV=mit+'resources/lecture-videos/';
  const mitN=mit+'pages/lecture-notes/';
  const usaco='https://usaco.guide/';
  const cses='https://cses.fi/problemset/list/';
  const gml='https://developers.google.com/machine-learning/crash-course';
  const kag='https://www.kaggle.com/learn';
  const vceVideo='https://video-lectures.vardhaman.org/';
  const t=(id,year,sem,track,icon,title,desc,video,vtitle,notes,practice,concept,duration)=>({id,year,sem,track,icon,title,desc,video,vtitle,notes,practice,concept,duration});
  const topics=[
    t('python',1,1,'AI & Data','🐍','Python programming foundations','Types, control flow, functions, collections, files, debugging and writing readable scripts.','https://www.kaggle.com/learn/python','Kaggle Python course','https://docs.python.org/3/tutorial/','https://www.hackerrank.com/domains/python','Write small functions, test edge cases, then compose them into a script. Learn the language before copying ML code.','3–5 weeks'),
    t('cprog',1,1,'DSA','⌨','Programming problem solving','Translate a problem into inputs, state, steps, output, and a tested program. Practice C/C++ or your college language.','https://www.youtube.com/channel/UCjDLYQh2r-4nHxDmQsOIsGQ/playlists','NPTEL lecture playlists','https://beej.us/guide/bgc/','https://www.hackerrank.com/domains/c','Before coding, write two examples by hand; after coding, test boundaries and invalid assumptions.','3–4 weeks'),
    t('math',1,1,'AI & Data','∑','Calculus & linear algebra','Vectors, matrices, derivatives, gradients, eigenvectors and the geometry behind model training.','https://ocw.mit.edu/courses/18-06-linear-algebra-spring-2010/','MIT 18.06 lecture videos','https://ocw.mit.edu/courses/18-06-linear-algebra-spring-2010/pages/readings/','https://www.khanacademy.org/math/linear-algebra','For every matrix operation, ask what transformation it represents; connect a gradient to the direction of fastest change.','6–8 weeks'),
    t('stats',1,2,'AI & Data','◌','Probability & statistics','Distributions, expectation, variance, sampling, confidence, Bayes rule and hypothesis tests.','https://www.youtube.com/@statquest/playlists','StatQuest statistics videos','https://www.openintro.org/book/os/','https://www.khanacademy.org/math/statistics-probability','Keep a assumptions/interpretation note with every test. Statistical significance is not the same as practical importance.','5–7 weeks'),
    t('git',1,2,'Web','⌘','Git, GitHub & command line','Terminal basics, commits, branches, issues, pull requests, Markdown and project documentation.','https://skills.github.com/','GitHub Skills guided lessons','https://docs.github.com/en/get-started/using-git/about-git','https://github.com/skills/introduction-to-github','Make small commits with useful messages; use branches before experiments; keep secrets out of repositories.','2 weeks'),
    t('web',1,2,'Web','◇','Web fundamentals & portfolio','HTML structure, CSS layout, JavaScript basics, accessibility and publishing a simple portfolio.','https://developer.mozilla.org/en-US/docs/Learn_web_development','MDN guided learning','https://developer.mozilla.org/en-US/docs/Web','https://www.freecodecamp.org/learn/2022/responsive-web-design/','Build one responsive page from scratch. Check keyboard navigation and mobile width before adding libraries.','4–6 weeks'),
    t('discrete',1,2,'DSA','∴','Discrete math & logic','Sets, relations, functions, induction, combinatorics, graphs and propositional logic.','https://ocw.mit.edu/courses/6-042j-mathematics-for-computer-science-spring-2015/','MIT Mathematics for CS','https://ocw.mit.edu/courses/6-042j-mathematics-for-computer-science-spring-2015/pages/readings/','https://open.kattis.com/','For each theorem, learn the proof idea, not just the final formula. Use induction to reason about recursive programs.','4–6 weeks'),
    t('complexity',2,3,'DSA','◷','Algorithm analysis & arrays','Big O, time/space tradeoffs, prefix sums, two pointers, sliding windows and invariants.','https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2020/resources/lecture-1-algorithms-and-computation/','MIT 6.006: Algorithms & computation','https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2020/pages/lecture-notes/','https://cses.fi/problemset/list/','Estimate work from input limits first. Define the invariant your loop preserves and explain why it is true.','4 weeks'),
    t('sorting',2,3,'DSA','↕','Sorting & binary search','Comparison sorting, stable ordering, binary search on answers, interval patterns and proof of monotonicity.','https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2020/resources/lecture-3-sets-and-sorting/','MIT 6.006: Sets & sorting','https://cp-algorithms.com/','https://cses.fi/problemset/list/','Binary search is a way to locate a boundary in a monotone predicate. State the predicate and loop invariant.','3 weeks'),
    t('hashing',2,3,'DSA','#','Hash maps & strings','Hashing, frequency tables, collision tradeoffs, string matching, prefix functions and rolling hashes.','https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2020/resources/lecture-4-hashing/','MIT 6.006: Hashing','https://cp-algorithms.com/string/string-hashing.html','https://cses.fi/problemset/list/','Use a map to trade memory for fast lookup. Know when collisions or adversarial input affect expected-time claims.','3 weeks'),
    t('trees',2,3,'DSA','♧','Trees, heaps & priority queues','Tree traversals, BST reasoning, balanced trees, heaps, tries and range-query structure selection.','https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2020/resources/lecture-8-binary-heaps/','MIT 6.006: Binary heaps','https://cp-algorithms.com/data_structures/segment_tree.html','https://cses.fi/problemset/list/','Choose the structure from the operations you need: ordered queries, top-k, prefix lookup, or range aggregation.','4 weeks'),
    t('graphs',2,4,'DSA','⌘','Graph traversal & connectivity','Representations, BFS/DFS, connected components, topological order, bipartite checks and DSU.','https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2020/resources/lecture-9-breadth-first-search/','MIT 6.006: BFS','https://cp-algorithms.com/graph/breadth-first-search.html','https://cses.fi/problemset/list/','Match the graph model to the problem. BFS handles unweighted shortest paths; DFS helps reveal structure.','4 weeks'),
    t('shortest',2,4,'DSA','⇢','Shortest paths & graph algorithms','Dijkstra, Bellman–Ford, Floyd–Warshall, minimum spanning trees and when each algorithm applies.','https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2020/resources/lecture-13-dijkstra/','MIT 6.006: Dijkstra','https://cp-algorithms.com/graph/dijkstra.html','https://cses.fi/problemset/list/','Check edge weights and negative cycles before choosing Dijkstra. Explain why relaxing edges improves a distance estimate.','3 weeks'),
    t('dp',2,4,'DSA','▦','Dynamic programming','State design, transitions, base cases, memoization, tabulation, knapsack, LIS, grid and interval patterns.','https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2020/resources/lecture-15-dynamic-programming-part-1-srtbot-fib-dags-bowling/','MIT 6.006: DP lecture 1','https://cp-algorithms.com/dynamic_programming/intro-to-dp.html','https://atcoder.jp/contests/dp/tasks','Write state, recurrence, base case, order and complexity before implementing. Trace a tiny input to test the transition.','5–7 weeks'),
    t('sql',2,3,'AI & Data','▤','SQL & relational data','Relational models, joins, aggregation, constraints, indexes, normalization and transaction basics.','https://www.youtube.com/@techTFQ/playlists','techTFQ · SQL lessons','https://www.postgresql.org/docs/current/tutorial.html','https://sqlbolt.com/','For each query, describe the grain of each table and predict row multiplication before you join.','3 weeks'),
    t('pandas',2,4,'AI & Data','▦','Data wrangling with Python & pandas','Load, inspect, clean, join, group and validate tabular data using Python, pandas and NumPy.','https://www.kaggle.com/learn/pandas','Kaggle pandas micro-course','https://pandas.pydata.org/docs/user_guide/','https://www.kaggle.com/learn/pandas','Never trust a dataset unseen: inspect missingness, duplicates, units, target leakage and train/test boundaries.','4 weeks'),
    t('viz',2,4,'AI & Data','◫','Data visualization & storytelling','Choose a chart for the question, build readable plots, explain uncertainty and tell a decision-focused data story.','https://www.kaggle.com/learn/data-visualization','Kaggle visualization course','https://clauswilke.com/dataviz/','https://observablehq.com/@observablehq/plot-gallery','Every chart needs a question, units, source, and one sentence that says what the reader should notice.','2–3 weeks'),
    t('dbms',2,4,'Core CS','▣','Database systems','Indexes, query planning, transactions, concurrency, isolation levels, recovery and schema design.','https://15445.courses.cs.cmu.edu/fall2025/','CMU Database Systems lectures','https://15445.courses.cs.cmu.edu/fall2025/slides/','https://15445.courses.cs.cmu.edu/fall2025/project1/','Understand why an index speeds one workload and slows writes; use transactions to state correctness guarantees.','4 weeks'),
    t('os',2,4,'Core CS','▧','Operating systems','Processes, threads, virtual memory, synchronization, filesystems, scheduling and system calls.','https://pdos.csail.mit.edu/6.1810/2023/schedule.html','MIT 6.1810 lecture schedule','https://pages.cs.wisc.edu/~remzi/OSTEP/','https://pages.cs.wisc.edu/~remzi/OSTEP/','Draw the process/thread state and memory layout before reasoning about a concurrency bug.','5 weeks'),
    t('networks',2,4,'Core CS','⌁','Computer networks','Layering, TCP/UDP, DNS, HTTP, routing, congestion, TLS and practical client/server debugging.','https://cs144.github.io/','Stanford CS144 lectures','https://gaia.cs.umass.edu/kurose_ross/online_lectures.htm','https://cs144.github.io/','Use packet flow to reason: who speaks next, which layer handles it, and what state can be lost?','4 weeks'),
    t('eda',3,5,'AI & Data','⌕','Exploratory data analysis','Ask testable questions, visualize distributions, detect outliers, compare groups and record data provenance.','https://www.kaggle.com/learn/data-cleaning','Kaggle data cleaning lessons','https://wesmckinney.com/book/','https://www.kaggle.com/competitions','Write an EDA memo with three observations, two caveats, and one next experiment—not a chart dump.','2–3 weeks'),
    t('ml',3,5,'AI & Data','✧','Machine learning fundamentals','Supervised and unsupervised learning, linear/logistic regression, trees, clustering, regularization and gradients.','https://developers.google.com/machine-learning/crash-course','Google ML Crash Course videos & exercises','https://developers.google.com/machine-learning/crash-course','https://www.kaggle.com/learn/intro-to-machine-learning','Start with a simple baseline. Match the model to the data and question, then compare with a held-out set.','6–8 weeks'),
    t('eval',3,5,'AI & Data','✓','Model evaluation & responsible AI','Splits, cross-validation, metrics, imbalance, calibration, leakage, fairness, privacy and reproducibility.','https://developers.google.com/machine-learning/crash-course/classification/accuracy-precision-recall','Google classification modules','https://developers.google.com/machine-learning/crash-course/overfitting/overfitting','https://www.kaggle.com/learn/intro-to-machine-learning','Choose the metric from the cost of errors. Separate data decisions from model decisions and document both.','3 weeks'),
    t('feature',3,5,'AI & Data','⌘','Feature engineering & classical ML','Encoding, scaling, leakage-safe transformations, feature selection, ensembles and experiment tracking.','https://www.youtube.com/@statquest/playlists','StatQuest ML lecture series','https://scikit-learn.org/stable/user_guide.html','https://www.kaggle.com/learn/intermediate-machine-learning','Build preprocessing inside a pipeline fitted only on training folds. Keep a reproducible baseline.','4 weeks'),
    t('deep-learning',3,6,'AI & Data','◉','Deep learning & neural networks','Backpropagation, optimization, regularization, CNNs, sequence models and practical PyTorch training.','https://course.fast.ai/','fast.ai Practical Deep Learning lectures','https://d2l.ai/','https://pytorch.org/tutorials/beginner/basics/intro.html','Make one tiny model overfit a tiny batch. If it cannot, debug the data and training loop first.','6–8 weeks'),
    t('nlp',3,6,'AI & Data','▰','NLP & transformers','Tokenization, embeddings, attention, transformers, fine-tuning, retrieval and careful evaluation.','https://huggingface.co/learn/llm-course','Hugging Face course lessons','https://jalammar.github.io/illustrated-transformer/','https://huggingface.co/learn/llm-course/chapter1/1','Evaluate with held-out examples and failure categories. Record model, prompt, data and version.','5–7 weeks'),
    t('vision',3,6,'AI & Data','▣','Computer vision','Image representations, convolution, augmentation, transfer learning, detection and responsible dataset use.','https://huggingface.co/learn/computer-vision-course','Hugging Face CV course','https://cs231n.github.io/','https://pytorch.org/tutorials/beginner/blitz/cifar10_tutorial.html','Inspect sample images and label quality; always compare transfer learning with a simpler baseline.','4–6 weeks'),
    t('dataeng',3,6,'AI & Data','⇧','Data engineering & pipelines','Ingestion, validation, batch/stream concepts, warehouses, orchestration, data quality and reproducible datasets.','https://www.youtube.com/@DataTalksClub/playlists','DataTalksClub · data engineering lessons','https://github.com/DataTalksClub/data-engineering-zoomcamp','https://github.com/DataTalksClub/data-engineering-zoomcamp','Treat data as a product: schema, owner, freshness, quality checks, lineage and recovery.','5 weeks'),
    t('cloud',3,6,'Web','☁','APIs, cloud & deployment','Build an API, containerize a service, use environment variables, deploy safely and monitor behavior.','https://cloud.google.com/learn/training','Google Cloud learning paths','https://fastapi.tiangolo.com/tutorial/','https://cloud.google.com/run/docs/quickstarts','Keep credentials server-side. Write a health endpoint and document setup before calling a project deployable.','4 weeks'),
    t('llm',4,7,'AI & Data','✳','Generative AI, LLM apps & RAG','Model behavior, prompting, retrieval, embeddings, grounding, tool use, evals, privacy and human review.','https://huggingface.co/learn/agents-course','Hugging Face Agents course','https://platform.openai.com/docs/guides/text','https://github.com/openai/openai-cookbook','Treat generated output as uncertain. Test grounded answers, refusal behavior, privacy and tool permissions.','5–7 weeks'),
    t('mlops',4,7,'AI & Data','⛭','MLOps & model monitoring','Version data/models, track experiments, package inference, test deployment, monitor drift and roll back.','https://fullstackdeeplearning.com/course/2022/','Full Stack Deep Learning lectures','https://ml-ops.org/','https://madewithml.com/','A model is one part of a service. Track input quality, latency, errors, cost and outcome drift.','4–6 weeks'),
    t('research',4,7,'AI & Data','⌕','Research literacy & reproducible experiments','Read papers, understand baselines, reproduce claims, handle citations, dataset licenses and limitations.','https://www.youtube.com/@YannicKilcher/playlists','Yannic Kilcher · paper discussions','https://arxiv.org/abs/2002.06720','https://paperswithcode.com/','Separate what the paper shows from what you infer. Record the setup so a teammate can reproduce it.','Ongoing'),
    t('capstone',4,8,'AI & Data','✦','Capstone, portfolio & technical writing','Find a real user, scope a useful system, build, evaluate, document, demo, and reflect on limitations.','https://www.youtube.com/@TraversyMedia/playlists','Traversy Media · project demos','https://developers.google.com/tech-writing','https://github.com/firstcontributions/first-contributions','Ship a small end-to-end project with a demo, README, architecture diagram, tests, and honest evaluation.','Semester-long'),
    t('communication',1,1,'Career','◖','Communication, writing & presentation','Clear emails, technical notes, explanations, listening, teamwork, interviews, demos and responsible disagreement.','https://www.youtube.com/@TED/playlists','TED · communication and ideas','https://developers.google.com/tech-writing','https://owl.purdue.edu/owl/subject_specific_writing/professional_technical_writing/index.html','Explain one engineering idea in 60 seconds, then ask a listener what remained unclear. Improve that sentence.','Practice weekly'),
    t('interview',3,6,'Career','◇','Interview readiness & job search','Resume evidence, project walkthroughs, DSA interviews, behavioral stories, mock interviews and thoughtful outreach.','https://www.youtube.com/@ApnaCollegeOfficial/playlists','Apna College · interview preparation','https://www.techinterviewhandbook.org/','https://leetcode.com/studyplan/top-interview-150/','For every claim on your resume, prepare one specific example, your decision, tradeoff, result and lesson.','6 weeks + repeat'),
    t('hack-build',2,4,'Career','✦','Hackathon teamwork & product craft','Find users, turn a theme into a testable problem, split work, prototype fast, demo clearly and submit on time.','https://www.youtube.com/@Devfolio/playlists','Devfolio · hackathon building and pitching','https://guide.devfolio.co/docs/guide/introduction','https://devpost.com/hackathons','Build one complete happy path before adding more features. Practice the demo with a fresh browser and a timer.','One weekend')
  ];

  const years=[
    {year:1,name:'Year 1 · Foundations',outcome:'Write code, think in math, learn how you learn.',semesters:[
      {title:'Semester 1',skills:['Python programming foundations','Programming problem solving','Calculus & linear algebra','Communication, writing & presentation'],project:'Mini build: a command-line or small web app that solves a problem you actually have.'},
      {title:'Semester 2',skills:['Discrete math & logic','Web fundamentals & portfolio','Git, GitHub & command line','Probability & statistics'],project:'Publish a simple portfolio with one project, a clear README and a short demo.'}]},
    {year:2,name:'Year 2 · Computer science & data fluency',outcome:'Use core systems and data structures with confidence.',semesters:[
      {title:'Semester 3',skills:['Algorithm analysis & arrays','Sorting & binary search','Hash maps & strings','SQL & relational data','Database systems'],project:'Build a data-backed application with a clean schema and a tested query path.'},
      {title:'Semester 4',skills:['Trees, heaps & priority queues','Graph traversal & connectivity','Shortest paths & graph algorithms','Dynamic programming','Operating systems','Computer networks','Data wrangling with Python & pandas','Data visualization & storytelling'],project:'Analyze a real dataset; share the notebook, data checks and a concise decision-focused story.'}]},
    {year:3,name:'Year 3 · AI, analytics & shipped systems',outcome:'Train models, evaluate them honestly, build for real users.',semesters:[
      {title:'Semester 5',skills:['Exploratory data analysis','Machine learning fundamentals','Model evaluation & responsible AI','Feature engineering & classical ML'],project:'Run a baseline-to-improvement ML study with a leakage-safe pipeline and error analysis.'},
      {title:'Semester 6',skills:['Deep learning & neural networks','NLP & transformers','Computer vision','Data engineering & pipelines','APIs, cloud & deployment','Interview readiness & job search'],project:'Deploy one AI/data product. Add a test set, latency/cost notes, docs and a live demo.'}]},
    {year:4,name:'Year 4 · Specialize, lead & launch',outcome:'Show depth, ownership, communication and evidence.',semesters:[
      {title:'Semester 7',skills:['Generative AI, LLM apps & RAG','MLOps & model monitoring','Research literacy & reproducible experiments','Hackathon teamwork & product craft'],project:'Choose a focus: AI engineering, data science, data engineering, research or software; build depth.'},
      {title:'Semester 8',skills:['Capstone, portfolio & technical writing','Interview readiness & job search','Communication, writing & presentation','Specialization deep dive'],project:'Complete a user-tested capstone and prepare a portfolio, technical walkthrough and next-step plan.'}]}
  ];

  const platforms=[
    {icon:'◉',name:'Codeforces',desc:'Regular contests with a rating ladder. Upsolve problems you missed.',url:'https://codeforces.com/contests',tag:'Timed contests'},
    {icon:'▤',name:'CSES Problem Set',desc:'A structured set for sorting, graphs, DP, range queries and more.',url:cses,tag:'Topic practice'},
    {icon:'⌘',name:'USACO Guide',desc:'Free lessons with implementations and ranked practice sets.',url:usaco,tag:'Guided path'},
    {icon:'▦',name:'AtCoder DP contest',desc:'A focused progression of classic dynamic programming problems.',url:'https://atcoder.jp/contests/dp/tasks',tag:'DP practice'},
    {icon:'⚡',name:'LeetCode study plans',desc:'Interview-focused problem lists and timed practice.',url:'https://leetcode.com/studyplan/',tag:'Interview prep'},
    {icon:'◧',name:'HackerRank',desc:'Language, SQL and interview preparation tracks.',url:'https://www.hackerrank.com/interview/preparation-kits',tag:'Skill drills'}
  ];

  const collegeLinks=[
    {icon:'⌂',name:'Vardhaman official college site',detail:'Start here for current programme information and official notices',url:'https://vardhaman.org/'},
    {icon:'▶',name:'Vardhaman video lectures',detail:'Official discipline-wise online lecture index',url:vceVideo},
    {icon:'▦',name:'Academic calendars',detail:'Official IQAC calendar archive',url:'https://iqac.vardhaman.org/calendars/'},
    {icon:'▤',name:'Library & previous papers',detail:'Library resources and old question papers',url:'https://vardhaman.org/library/'},
    {icon:'↗',name:'Career Development Cell',detail:'Placements, internships and training courses',url:'https://cdc.vardhaman.org/'},
    {icon:'✦',name:'Student clubs & activities',detail:'Explore student organizations and events',url:'https://clubs.vardhaman.org/'},
    {icon:'⌕',name:'ACM Student Chapter',detail:'Technical talks, coding and community',url:'https://acm.vardhaman.org/'},
    {icon:'◈',name:'NPTEL local chapter',detail:'Course enrollment and campus support',url:'https://nptel.vardhaman.org/'},
    {icon:'▧',name:'Official academics portal',detail:'Academic office and learning information',url:'https://academics.vardhaman.org/'},
    {icon:'⌘',name:'Student circulars & notices',detail:'Official academic and campus announcements',url:'https://studentscorner.vardhaman.org/src_programs/students_corner/x-BulletinBoard/student_circular.php'}
  ];

  const careerYears=[
    {year:'Year 1',title:'Build the base',outcome:'Programming fluency · Math · Communication · Git',items:[
      ['Code every week','Finish one introductory language path; solve small problems; build two tiny utilities.',['Python','C / C++','GitHub']],
      ['Communicate clearly','Keep a weekly engineering journal; explain a concept to a classmate; practice short presentations.',['Writing','Speaking','Teamwork']],
      ['Protect academic fundamentals','Use official syllabus and exam calendar; build spaced review into every week.',['Exam plan','Notes','Revision']]
    ]},
    {year:'Year 2',title:'Become dependable',outcome:'DSA · Core CS · SQL · First team projects',items:[
      ['DSA with deliberate practice','Learn patterns, solve by topic, join regular contests, and review misses rather than chasing counts.',['CSES','Codeforces','LeetCode']],
      ['Know how software works','Study DBMS, OS and networks; explain one tradeoff and one failure mode per topic.',['DBMS','OS','Networks']],
      ['Make a useful data product','Clean data, build simple charts, define users and document the decisions.',['SQL','pandas','Visualization']]
    ]},
    {year:'Year 3',title:'Show AI/data depth',outcome:'One specialization · Internship proof · Public portfolio',items:[
      ['Build ML foundations before chasing trends','Establish baselines, evaluate carefully, inspect failures, and understand the math.',['ML','Statistics','Evaluation']],
      ['Ship one end-to-end project','Expose an API or app, deploy it, write a clear README and make the demo reproducible.',['API','Cloud','Monitoring']],
      ['Get feedback from the field','Apply to internships, attend department/ACM events, ask for code review, and present your work.',['Internship','Mentor','Demo']]
    ]},
    {year:'Year 4',title:'Turn proof into opportunity',outcome:'Capstone · Interview readiness · Clear communication',items:[
      ['Finish a strong capstone','Solve a real problem, document evidence, user test, limitations, data rights and next steps.',['Research','Product','Writing']],
      ['Prepare for multiple interview formats','Practice DSA, SQL, ML/system design, project walkthroughs and behavioral stories.',['Mock interview','Resume','Story bank']],
      ['Build a healthy application loop','Use Vardhaman CDC, alumni, official openings and internships; track attempts and learning.',['CDC','Applications','Network']]
    ]}
  ];

  const directory=[
    {category:'Vardhaman · official',resources:collegeLinks.map(x=>({icon:x.icon,name:x.name,desc:x.detail,url:x.url,tag:'Official VCE'}))},
    {category:'AI & data science learning',resources:[
      ['◉','Google ML Crash Course','Videos, interactive lessons, exercises and ML foundations.',gml,'Free course'],['▦','Kaggle Learn','Short practical courses: Python, pandas, SQL, visualization and ML.',kag,'Hands-on'],['✧','Hugging Face Learn','LLMs, agents, computer vision, robotics and open-source AI.', 'https://huggingface.co/learn','Open source'],['◇','fast.ai','Practical deep learning lessons and notebooks.','https://course.fast.ai/','Free course'],['▧','PyTorch tutorials','Official recipes and beginner-to-advanced walkthroughs.','https://pytorch.org/tutorials/','Documentation'],['⌘','scikit-learn user guide','Classical machine learning concepts and practical examples.','https://scikit-learn.org/stable/user_guide.html','Documentation'],['◈','DataTalksClub Zoomcamp','Project-oriented data engineering and ML engineering courses.','https://github.com/DataTalksClub','Community courses'],['▤','OpenIntro Statistics','Free open statistics textbook and supporting material.','https://www.openintro.org/book/os/','Free textbook']].map(r=>({icon:r[0],name:r[1],desc:r[2],url:r[3],tag:r[4]}))},
    {category:'Algorithms & coding practice',resources:platforms.map(x=>({icon:x.icon,name:x.name,desc:x.desc,url:x.url,tag:x.tag})).concat([
      {icon:'◷',name:'MIT Introduction to Algorithms',desc:'Lecture videos, notes, quizzes and problem sets for core algorithms.',url:mit+'resources/lecture-videos/',tag:'University course'},
      {icon:'⌘',name:'CP-Algorithms',desc:'Reference notes for algorithms and data structures.',url:'https://cp-algorithms.com/',tag:'Reference'},
      {icon:'◫',name:'GitHub Skills',desc:'Interactive GitHub lessons: repositories, Markdown, PRs and Pages.',url:'https://skills.github.com/',tag:'Interactive'}
    ])},
    {category:'Communication, career & writing',resources:[
      {icon:'✎',name:'Google Technical Writing',desc:'Practical courses for clear technical documents and explanations.',url:'https://developers.google.com/tech-writing','tag':'Writing'},
      {icon:'◖',name:'Purdue OWL: Technical writing',desc:'Guidance on professional writing, reports and documentation.',url:'https://owl.purdue.edu/owl/subject_specific_writing/professional_technical_writing/index.html',tag:'Writing'},
      {icon:'◉',name:'Toastmasters learning resources',desc:'Practice public speaking, listening and structured storytelling.',url:'https://www.toastmasters.org/resources','tag':'Speaking'},
      {icon:'↗',name:'Technical Interview Handbook',desc:'A structured guide to applications, DSA interviews and behavioral rounds.',url:'https://www.techinterviewhandbook.org/','tag':'Career'},
      {icon:'✦',name:'Google interview prep',desc:'Official resources for technical interview practice and preparation.',url:'https://careers.google.com/how-we-hire/','tag':'Interview'},
      {icon:'▤',name:'Vardhaman CDC',desc:'Campus placement preparation, internships and career training.',url:'https://cdc.vardhaman.org/','tag':'Vardhaman'}
    ]},
    {category:'Build, collaborate & find opportunities',resources:[
      {icon:'⌘',name:'GitHub Skills',desc:'Practice repositories, branches, pull requests and Markdown.',url:'https://skills.github.com/','tag':'Git'},
      {icon:'✦',name:'Devpost hackathons',desc:'Discover public online and in-person hackathons.',url:'https://devpost.com/hackathons','tag':'Hackathons'},
      {icon:'◈',name:'Devfolio discover',desc:'India-focused hackathons and builder events.',url:'https://devfolio.co/discover','tag':'Hackathons'},
      {icon:'⚡',name:'Unstop hackathons',desc:'Student competitions, hackathons and campus opportunities.',url:'https://unstop.com/hackathons','tag':'India'},
      {icon:'◉',name:'Major League Hacking',desc:'Student hackathon seasons and Global Hack Week challenges.',url:'https://www.mlh.com/events','tag':'Community'},
      {icon:'◌',name:'Vardhaman clubs',desc:'Find technical clubs, peer groups and campus activities.',url:'https://clubs.vardhaman.org/','tag':'Campus'}
    ]}
  ].map(cat=>({category:cat.category,resources:cat.resources.map(x=>Array.isArray(x)?({icon:x[0],name:x[1],desc:x[2],url:x[3],tag:x[4]}):x)}));

  const hackSources=[
    {id:'unstop',name:'Unstop · India',url:'https://unstop.com/hackathons',hint:'Student hackathons, datathons, coding contests and campus events in India'},
    {id:'devfolio',name:'Devfolio · India',url:'https://devfolio.co/discover',hint:'India-focused builder events and organizer listings'},
    {id:'devpost',name:'Devpost · Global',url:'https://devpost.com/hackathons',hint:'Online and in-person events; includes live challenge deadlines'},
    {id:'mlh',name:'MLH · student events',url:'https://mlh.io/seasons/2026/events',hint:'Verified collegiate hackathon season and Global Hack Week'},
    {id:'hackerearth',name:'HackerEarth · challenges',url:'https://www.hackerearth.com/challenges/',hint:'Company coding challenges, hackathons and hiring events'},
    {id:'hackclub',name:'Hack Club · student',url:'https://hackclub.com/events/',hint:'Student-led hackathons, hack nights and build opportunities'},
    {id:'kaggle',name:'Kaggle · data & ML',url:'https://www.kaggle.com/competitions',hint:'Live machine-learning competitions and data challenges'},
    {id:'aicrowd',name:'AIcrowd · AI research',url:'https://www.aicrowd.com/challenges',hint:'Research and machine-learning challenges'},
    {id:'zindi',name:'Zindi · data science',url:'https://zindi.africa/competitions',hint:'Data science competitions with real datasets'},
    {id:'company',name:'Company builder challenges',url:'https://devpost.com/c/artificial-intelligence',hint:'Live company-hosted build challenges on the Devpost AI index'},
    {id:'social',name:'Social event discovery',url:'https://www.linkedin.com/search/results/content/?keywords=hackathon%20registration',hint:'Organizer posts and community announcements; verify each organizer before applying'},
    {id:'x',name:'X · public announcements',url:'https://x.com/search?q=hackathon%20registration&src=typed_query&f=live',hint:'Live public posts for hackathons; dates and eligibility are unverified until opened on organizer pages'}
  ];
  const cfTags={complexity:['implementation','math'],sorting:['binary search','sortings'],hashing:['strings','hashing'],trees:['dfs and similar','trees'],graphs:['dfs and similar','graphs'],shortest:['shortest paths','graphs'],dp:['dp'],discrete:['combinatorics','math'],interview:['implementation','greedy']};
  const problemPicks={
    python:[['HackerRank · Say "Hello, World!" With Python','Warm-up','https://www.hackerrank.com/challenges/py-hello-world/problem'],['HackerRank · List Comprehensions','Easy','https://www.hackerrank.com/challenges/list-comprehensions/problem'],['Kaggle · Python exercises','Guided','https://www.kaggle.com/learn/python']],
    cprog:[['HackerRank · Solve Me First','Warm-up','https://www.hackerrank.com/challenges/solve-me-first/problem'],['HackerRank · Simple Array Sum','Easy','https://www.hackerrank.com/challenges/simple-array-sum/problem'],['HackerRank · C practice','Guided','https://www.hackerrank.com/domains/c']],
    math:[['Khan Academy · Linear algebra practice','Guided','https://www.khanacademy.org/math/linear-algebra'],['MIT 18.06 · Problem sets','Guided','https://ocw.mit.edu/courses/18-06-linear-algebra-spring-2010/pages/assignments/'],['OpenIntro · Statistics exercises','Guided','https://www.openintro.org/book/os/']],
    stats:[['Khan Academy · Statistics & probability','Guided','https://www.khanacademy.org/math/statistics-probability'],['OpenIntro · Practice problems','Guided','https://www.openintro.org/book/os/'],['HackerRank · 10 Days of Statistics','Series','https://www.hackerrank.com/domains/tutorials/10-days-of-statistics']],
    git:[['GitHub Skills · Introduction to GitHub','Guided','https://github.com/skills/introduction-to-github'],['GitHub Skills · Markdown','Guided','https://github.com/skills/communicate-using-markdown'],['First Contributions · open source PR','Guided','https://github.com/firstcontributions/first-contributions']],
    web:[['freeCodeCamp · Responsive Web Design','Guided','https://www.freecodecamp.org/learn/2022/responsive-web-design/'],['MDN · Test your skills','Guided','https://developer.mozilla.org/en-US/docs/Learn_web_development'],['Frontend Mentor · Project challenges','Project','https://www.frontendmentor.io/challenges']],
    discrete:[['Kattis · Problem archive','Warm-up','https://open.kattis.com/problems'],['MIT 6.042J · Assignments','Guided','https://ocw.mit.edu/courses/6-042j-mathematics-for-computer-science-spring-2015/pages/assignments/'],['CSES · Introductory problems','Easy','https://cses.fi/problemset/list/']],
    complexity:[['Codeforces 4A · Watermelon','800 · Warm-up','https://codeforces.com/problemset/problem/4/A'],['CSES · Weird Algorithm','Warm-up','https://cses.fi/problemset/task/1068/'],['HackerRank · Arrays DS','Easy','https://www.hackerrank.com/challenges/arrays-ds/problem']],
    sorting:[['CSES · Distinct Numbers','Warm-up','https://cses.fi/problemset/task/1621/'],['Codeforces 339A · Helpful Maths','800 · Warm-up','https://codeforces.com/problemset/problem/339/A'],['HackerRank · Intro to Tutorial Challenges','Easy','https://www.hackerrank.com/challenges/tutorial-intro/problem']],
    hashing:[['Codeforces 4C · Registration System','1300 · Medium','https://codeforces.com/problemset/problem/4/C'],['HackerRank · Ransom Note','Easy','https://www.hackerrank.com/challenges/ctci-ransom-note/problem'],['CSES · Distinct Numbers','Warm-up','https://cses.fi/problemset/task/1621/']],
    trees:[['CSES · Subordinates','Medium','https://cses.fi/problemset/task/1674/'],['CSES · Tree Matching','Medium','https://cses.fi/problemset/task/1130/'],['HackerRank · Tree: Height of a Binary Tree','Easy','https://www.hackerrank.com/challenges/tree-height-of-a-binary-tree/problem']],
    graphs:[['CSES · Counting Rooms','Easy','https://cses.fi/problemset/task/1192/'],['CSES · Labyrinth','Easy','https://cses.fi/problemset/task/1193/'],['HackerRank · BFS: Shortest Reach','Medium','https://www.hackerrank.com/challenges/bfsshortreach/problem']],
    shortest:[['CSES · Shortest Routes I','Medium','https://cses.fi/problemset/task/1671/'],['Codeforces 20C · Dijkstra?','1600 · Challenge','https://codeforces.com/problemset/problem/20/C'],['CSES · High Score','Challenge','https://cses.fi/problemset/task/1673/']],
    dp:[['AtCoder DP A · Frog 1','Starter','https://atcoder.jp/contests/dp/tasks/dp_a'],['CSES · Dice Combinations','Easy','https://cses.fi/problemset/task/1633/'],['AtCoder DP D · Knapsack 1','Medium','https://atcoder.jp/contests/dp/tasks/dp_d']],
    sql:[['HackerRank · Select All','Warm-up','https://www.hackerrank.com/challenges/revising-the-select-query/problem'],['SQLBolt · Lesson 1','Warm-up','https://sqlbolt.com/lesson/select_queries_introduction'],['HackerRank · Basic Join','Easy','https://www.hackerrank.com/domains/sql']],
    pandas:[['Kaggle · Pandas exercises','Guided','https://www.kaggle.com/learn/pandas'],['Kaggle · Data Cleaning','Guided','https://www.kaggle.com/learn/data-cleaning'],['Pandas · Getting started tutorials','Guided','https://pandas.pydata.org/docs/getting_started/intro_tutorials/']],
    viz:[['Kaggle · Data Visualization','Guided','https://www.kaggle.com/learn/data-visualization'],['Observable · Plot gallery','Guided','https://observablehq.com/@observablehq/plot-gallery'],['Makeover Monday · Practice data stories','Project','https://makeovermonday.co.uk/']],
    dbms:[['CMU 15-445 · Database project','Guided','https://15445.courses.cs.cmu.edu/fall2025/project1/'],['HackerRank · SQL practice','Guided','https://www.hackerrank.com/domains/sql'],['SQLBolt · Interactive lessons','Guided','https://sqlbolt.com/']],
    os:[['OSTEP · Homework & projects','Guided','https://pages.cs.wisc.edu/~remzi/OSTEP/'],['MIT xv6 labs','Project','https://pdos.csail.mit.edu/6.1810/2023/'],['HackerRank · Linux Shell','Guided','https://www.hackerrank.com/domains/shell']],
    networks:[['Stanford CS144 · Course & labs','Guided','https://cs144.github.io/'],['Wireshark · Sample captures','Hands-on','https://www.wireshark.org/docs/'],['HackerRank · Linux Shell','Warm-up','https://www.hackerrank.com/domains/shell']],
    eda:[['Kaggle · Data cleaning exercises','Guided','https://www.kaggle.com/learn/data-cleaning'],['Kaggle · Beginner competitions','Project','https://www.kaggle.com/competitions'],['OpenML · Datasets','Project','https://www.openml.org/search?type=data']],
    ml:[['Kaggle · Intro to ML','Guided','https://www.kaggle.com/learn/intro-to-machine-learning'],['Google MLCC · Exercises','Guided','https://developers.google.com/machine-learning/crash-course'],['OpenML · benchmark datasets','Project','https://www.openml.org/search?type=data']],
    eval:[['Kaggle · Model validation','Guided','https://www.kaggle.com/learn/intermediate-machine-learning'],['Google MLCC · Classification','Guided','https://developers.google.com/machine-learning/crash-course/classification'],['Fairlearn · Tutorials','Guided','https://fairlearn.org/main/auto_examples/index.html']],
    feature:[['Kaggle · Intermediate ML','Guided','https://www.kaggle.com/learn/intermediate-machine-learning'],['scikit-learn · Pipelines','Guided','https://scikit-learn.org/stable/modules/compose.html'],['Kaggle · Feature engineering','Guided','https://www.kaggle.com/learn/feature-engineering']],
    'deep-learning':[['PyTorch · Beginner tutorials','Guided','https://pytorch.org/tutorials/beginner/basics/intro.html'],['fast.ai · Lesson notebooks','Guided','https://course.fast.ai/'],['Kaggle · Intro to Deep Learning','Guided','https://www.kaggle.com/learn/intro-to-deep-learning']],
    nlp:[['Hugging Face · LLM course','Guided','https://huggingface.co/learn/llm-course'],['scikit-learn · text analytics','Guided','https://scikit-learn.org/stable/modules/feature_extraction.html'],['Hugging Face · Tasks','Project','https://huggingface.co/tasks']],
    vision:[['PyTorch · CIFAR-10 tutorial','Guided','https://pytorch.org/tutorials/beginner/blitz/cifar10_tutorial.html'],['Hugging Face · CV course','Guided','https://huggingface.co/learn/computer-vision-course'],['Kaggle · Computer vision','Project','https://www.kaggle.com/competitions?tagIds=14102']],
    dataeng:[['DataTalksClub · Data engineering zoomcamp','Guided','https://github.com/DataTalksClub/data-engineering-zoomcamp'],['dbt · Jaffle Shop','Project','https://github.com/dbt-labs/jaffle_shop'],['Kaggle · datasets','Project','https://www.kaggle.com/datasets']],
    cloud:[['FastAPI · Tutorial','Guided','https://fastapi.tiangolo.com/tutorial/'],['Google Cloud · Cloud Run quickstart','Project','https://cloud.google.com/run/docs/quickstarts'],['GitHub Skills · Pages','Guided','https://github.com/skills/github-pages']],
    llm:[['Hugging Face · Agents course','Guided','https://huggingface.co/learn/agents-course'],['OpenAI Cookbook','Project','https://github.com/openai/openai-cookbook'],['RAG evaluation guide','Guided','https://platform.openai.com/docs/guides/evals']],
    mlops:[['Made With ML · MLOps course','Guided','https://madewithml.com/'],['Full Stack Deep Learning labs','Project','https://fullstackdeeplearning.com/course/2022/'],['MLflow · Getting started','Guided','https://mlflow.org/docs/latest/ml/getting-started/']],
    research:[['Papers with Code · Browse tasks','Research','https://paperswithcode.com/'],['arXiv · AI papers','Research','https://arxiv.org/list/cs.AI/recent'],['Reproducibility checklist','Guided','https://neurips.cc/public/guides/PaperChecklist']],
    capstone:[['GitHub · Good first issues','Open source','https://github.com/topics/good-first-issue'],['Devpost · Build challenges','Competition','https://devpost.com/hackathons'],['Google Technical Writing','Communication','https://developers.google.com/tech-writing']],
    communication:[['Toastmasters · Speech resources','Practice','https://www.toastmasters.org/resources/public-speaking-tips'],['Google · Technical writing course','Writing','https://developers.google.com/tech-writing/one'],['Purdue OWL · Professional writing','Writing','https://owl.purdue.edu/owl/subject_specific_writing/professional_technical_writing/index.html']],
    interview:[['LeetCode · Top Interview 150','Curated set','https://leetcode.com/studyplan/top-interview-150/'],['HackerRank · Interview Prep Kit','Curated set','https://www.hackerrank.com/interview/preparation-kits'],['Codeforces · Problemset','Practice','https://codeforces.com/problemset']],
    'hack-build':[['Devpost · Current hackathons','Opportunity','https://devpost.com/hackathons'],['Devfolio · Discover','Opportunity','https://devfolio.co/discover'],['HackerRank · Project Euler+','Practice','https://www.hackerrank.com/contests/projecteuler/challenges']]
  };
  const topicSearchTags={python:['Python'],dsa:['data structures','algorithms'],sql:['SQL'],ai:['artificial intelligence','machine learning'],datascience:['data science','data analysis'],communication:['communication skills','technical writing']};
  const langCourses=[
    {id:'c',name:'C',icon:'C',color:'lav',overview:'Memory, data structures, and a strong first-principles foundation.',topics:[
      {name:'Input, output & variables',video:'https://cs50.harvard.edu/x/weeks/1/',notes:'https://cs50.harvard.edu/x/weeks/1/',picks:[['HackerRank · Playing With Characters','Warm-up','https://www.hackerrank.com/challenges/playing-with-characters/problem'],['HackerRank · Sum and Difference','Warm-up','https://www.hackerrank.com/challenges/sum-numbers-c/problem']]},
      {name:'if / else, comparisons & logic',video:'https://cs50.harvard.edu/x/weeks/1/',notes:'https://vardhaman.org/library/',picks:[['HackerRank · Conditional Statements in C','Easy · if / else','https://www.hackerrank.com/challenges/conditional-statements-in-c/problem'],['HackerRank · Intro to Conditional Statements','Easy · branching','https://www.hackerrank.com/challenges/30-conditional-statements/problem'],['Codeforces · Team','800 · condition checks','https://codeforces.com/problemset/problem/231/A'],['Codeforces · Football','900 · adjacent condition scan','https://codeforces.com/problemset/problem/96/A']]},
      {name:'Loops & nested loops',video:'https://cs50.harvard.edu/x/weeks/1/',notes:'https://en.cppreference.com/w/c/language/for.html',picks:[['HackerRank · For Loop in C','Easy · loops','https://www.hackerrank.com/challenges/for-loop-in-c/problem'],['HackerRank · Sum of Digits of a Five Digit Number','Easy · loop + modulo','https://www.hackerrank.com/challenges/sum-of-digits-of-a-five-digit-number/problem'],['Codeforces · Nearly Lucky Number','800 · loops + conditions','https://codeforces.com/problemset/problem/110/A']]},
      {name:'Functions & scope',video:'https://cs50.harvard.edu/x/weeks/1/',notes:'https://en.cppreference.com/w/c/language/functions.html',picks:[['HackerRank · Functions in C','Easy · functions','https://www.hackerrank.com/challenges/functions-in-c/problem'],['HackerRank · Calculate the Nth term','Easy · recursive function','https://www.hackerrank.com/challenges/recursion-in-c/problem']]},
      {name:'Arrays & strings',video:'https://cs50.harvard.edu/x/weeks/2/',notes:'https://en.cppreference.com/w/c/language/array.html',picks:[['HackerRank · 1D Arrays in C','Easy · arrays','https://www.hackerrank.com/challenges/1d-arrays-in-c/problem'],['HackerRank · Printing Tokens','Easy · strings','https://www.hackerrank.com/challenges/printing-tokens-/problem'],['HackerRank · Arrays DS','Easy · array practice','https://www.hackerrank.com/challenges/arrays-ds/problem']]},
      {name:'Pointers & memory',video:'https://cs50.harvard.edu/x/weeks/4/',notes:'https://en.cppreference.com/w/c/language/pointer.html',picks:[['HackerRank · Pointers in C','Easy · pointers','https://www.hackerrank.com/challenges/pointer-in-c/problem'],['CS50 · Practice problems','Guided · memory','https://cs50.harvard.edu/x/2026/psets/4/']]}
    ]},
    {id:'cpp',name:'C++',icon:'C++',color:'teal',overview:'A strong interview and competitive programming language with STL.',topics:[
      {name:'Types, input & output',video:'https://www.youtube.com/channel/UCjDLYQh2r-4nHxDmQsOIsGQ/playlists',notes:'https://www.learncpp.com/',picks:[['HackerRank · Say Hello, World!','Warm-up','https://www.hackerrank.com/challenges/cpp-hello-world/problem'],['HackerRank · Input and Output','Easy','https://www.hackerrank.com/challenges/cpp-input-and-output/problem']]},
      {name:'if / else, switch & logic',video:'https://www.youtube.com/channel/UCjDLYQh2r-4nHxDmQsOIsGQ/playlists',notes:'https://www.learncpp.com/cpp-tutorial/introduction-to-if-statements/',picks:[['HackerRank · Conditional Statements','Easy · if / else','https://www.hackerrank.com/challenges/conditional-statements-in-c/problem'],['Codeforces · Watermelon','800 · conditions','https://codeforces.com/problemset/problem/4/A'],['Codeforces · Team','800 · logical operators','https://codeforces.com/problemset/problem/231/A']]},
      {name:'Loops & patterns',video:'https://www.youtube.com/channel/UCjDLYQh2r-4nHxDmQsOIsGQ/playlists',notes:'https://www.learncpp.com/',picks:[['HackerRank · For Loop in C','Easy · loop practice','https://www.hackerrank.com/challenges/for-loop-in-c/problem'],['Codeforces · Beautiful Matrix','800 · nested loops','https://codeforces.com/problemset/problem/263/A']]},
      {name:'Functions & recursion',video:'https://web.stanford.edu/class/archive/cs/cs106l/cs106l.1262/',notes:'https://www.learncpp.com/cpp-tutorial/introduction-to-functions/',picks:[['CSES · Tower of Hanoi','Easy · recursion','https://cses.fi/problemset/task/2165/'],['HackerRank · Recursion in C','Easy · recursive thinking','https://www.hackerrank.com/challenges/recursion-in-c/problem']]},
      {name:'Arrays, vector & strings',video:'https://web.stanford.edu/class/archive/cs/cs106l/cs106l.1262/',notes:'https://www.learncpp.com/cpp-tutorial/an-introduction-to-stdvector/',picks:[['Codeforces · Helpful Maths','800 · sorting strings','https://codeforces.com/problemset/problem/339/A'],['CSES · Missing Number','Warm-up · arrays','https://cses.fi/problemset/task/1083/'],['HackerRank · Arrays DS','Easy · arrays','https://www.hackerrank.com/challenges/arrays-ds/problem']]},
      {name:'Classes, STL & object design',video:'https://web.stanford.edu/class/archive/cs/cs106l/cs106l.1262/',notes:'https://www.learncpp.com/',picks:[['HackerRank · C++ Classes','Guided · OOP','https://www.hackerrank.com/domains/cpp'],['CSES · Sorting and Searching','Practice · STL','https://cses.fi/problemset/list/']]}
    ]},
    {id:'python',name:'Python',icon:'Py',color:'orange',overview:'The main tool for data science, automation and AI experiments.',topics:[
      {name:'Variables, types & input/output',video:'https://ocw.mit.edu/courses/6-0001-introduction-to-computer-science-and-programming-in-python-fall-2016/resources/lecture-videos/',notes:'https://docs.python.org/3/tutorial/introduction.html',picks:[['HackerRank · Say Hello, World! With Python','Warm-up','https://www.hackerrank.com/challenges/py-hello-world/problem'],['Kaggle · Python','Guided practice','https://www.kaggle.com/learn/python']]},
      {name:'if / elif / else & Boolean logic',video:'https://ocw.mit.edu/courses/6-0001-introduction-to-computer-science-and-programming-in-python-fall-2016/resources/lecture-videos/',notes:'https://docs.python.org/3/tutorial/controlflow.html#if-statements',picks:[['HackerRank · If-Else','Easy · conditionals','https://www.hackerrank.com/challenges/py-if-else/problem'],['HackerRank · Leap Year','Easy · compound conditions','https://www.hackerrank.com/challenges/write-a-function/problem'],['Codeforces · Watermelon','800 · even/odd condition','https://codeforces.com/problemset/problem/4/A']]},
      {name:'for / while loops',video:'https://ocw.mit.edu/courses/6-0001-introduction-to-computer-science-and-programming-in-python-fall-2016/resources/lecture-videos/',notes:'https://docs.python.org/3/tutorial/controlflow.html#for-statements',picks:[['HackerRank · Loops','Easy · repetition','https://www.hackerrank.com/challenges/python-loops/problem'],['HackerRank · Print Function','Easy · loop output','https://www.hackerrank.com/challenges/python-print/problem']]},
      {name:'Lists, tuples, sets & dictionaries',video:'https://ocw.mit.edu/courses/6-0001-introduction-to-computer-science-and-programming-in-python-fall-2016/resources/lecture-videos/',notes:'https://docs.python.org/3/tutorial/datastructures.html',picks:[['HackerRank · Lists','Easy · list operations','https://www.hackerrank.com/challenges/python-lists/problem'],['HackerRank · Finding the percentage','Easy · dictionaries','https://www.hackerrank.com/challenges/finding-the-percentage/problem'],['Kaggle · Python exercises','Guided','https://www.kaggle.com/learn/python']]},
      {name:'Functions, modules & testing',video:'https://cs50.harvard.edu/python/','notes':'https://docs.python.org/3/tutorial/controlflow.html#defining-functions',picks:[['HackerRank · Write a function','Easy · functions','https://www.hackerrank.com/challenges/write-a-function/problem'],['CS50P · Problem sets','Guided','https://cs50.harvard.edu/python/']]},
      {name:'Strings, files & exceptions',video:'https://cs50.harvard.edu/python/','notes':'https://docs.python.org/3/tutorial/inputoutput.html',picks:[['HackerRank · String Validators','Easy · strings','https://www.hackerrank.com/challenges/string-validators/problem'],['HackerRank · Text Wrap','Easy · string methods','https://www.hackerrank.com/challenges/text-wrap/problem']]},
      {name:'Classes, objects & OOP',video:'https://ocw.mit.edu/courses/6-0001-introduction-to-computer-science-and-programming-in-python-fall-2016/resources/lecture-videos/',notes:'https://docs.python.org/3/tutorial/classes.html',picks:[['HackerRank · Classes: Dealing with Complex Numbers','Easy · classes','https://www.hackerrank.com/challenges/class-1-dealing-with-complex-numbers/problem'],['Python practice track','Guided','https://www.hackerrank.com/domains/python']]}
    ]},
    {id:'java',name:'Java',icon:'J',color:'orange',overview:'Object-oriented programming, interview preparation and production software.',topics:[
      {name:'Types, input & output',video:'https://nptel.ac.in/courses/106105191',notes:'https://dev.java/learn/',picks:[['HackerRank · Welcome to Java!','Warm-up','https://www.hackerrank.com/challenges/welcome-to-java/problem'],['HackerRank · Java Stdin and Stdout I','Easy','https://www.hackerrank.com/challenges/java-stdin-and-stdout-1/problem']]},
      {name:'if / else & switch statements',video:'https://nptel.ac.in/courses/106105191',notes:'https://dev.java/learn/language-basics/controlling-flow/',picks:[['HackerRank · Java If-Else','Easy · if / else','https://www.hackerrank.com/challenges/java-if-else/problem'],['Codeforces · Team','800 · logical conditions','https://codeforces.com/problemset/problem/231/A']]},
      {name:'for / while loops',video:'https://nptel.ac.in/courses/106105191',notes:'https://dev.java/learn/language-basics/controlling-flow/',picks:[['HackerRank · Java Loops I','Easy · loops','https://www.hackerrank.com/challenges/java-loops-i/problem'],['HackerRank · Java Loops II','Easy · nested logic','https://www.hackerrank.com/challenges/java-loops/problem']]},
      {name:'Methods, arrays & strings',video:'https://nptel.ac.in/courses/106105191',notes:'https://dev.java/learn/language-basics/arrays/',picks:[['HackerRank · Java Datatypes','Easy · types','https://www.hackerrank.com/challenges/java-datatypes/problem'],['HackerRank · Java Subarray','Medium · arrays','https://www.hackerrank.com/challenges/java-negative-subarray/problem']]},
      {name:'Classes, inheritance & interfaces',video:'https://nptel.ac.in/courses/106105191',notes:'https://dev.java/learn/',picks:[['HackerRank · Java Inheritance I','Easy · inheritance','https://www.hackerrank.com/challenges/java-inheritance-1/problem'],['HackerRank · Java Abstract Class','Easy · abstraction','https://www.hackerrank.com/challenges/java-abstract-class/problem']]},
      {name:'Collections, exceptions & generics',video:'https://nptel.ac.in/courses/106105191',notes:'https://dev.java/learn/api/collections-framework/',picks:[['HackerRank · Java Arraylist','Easy · collections','https://www.hackerrank.com/challenges/java-arraylist/problem'],['HackerRank · Java Exception Handling','Easy','https://www.hackerrank.com/domains/java']]}
    ]},
    {id:'javascript',name:'JavaScript',icon:'JS',color:'lav',overview:'The web language for interactive applications, APIs and full-stack projects.',topics:[
      {name:'Values, types & console basics',video:'https://cs50.harvard.edu/x/2026/weeks/8/',notes:'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Grammar_and_types',picks:[['HackerRank · Hello World','Warm-up','https://www.hackerrank.com/challenges/js10-hello-world/problem'],['HackerRank · Data Types','Easy','https://www.hackerrank.com/challenges/js10-data-types/problem']]},
      {name:'if / else, switch & comparisons',video:'https://cs50.harvard.edu/x/2026/weeks/8/',notes:'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Control_flow_and_error_handling',picks:[['HackerRank · If-Else','Easy · conditionals','https://www.hackerrank.com/challenges/js10-if-else/problem'],['HackerRank · Switch','Easy · switch','https://www.hackerrank.com/challenges/js10-switch/problem']]},
      {name:'Loops & iteration',video:'https://cs50.harvard.edu/x/2026/weeks/8/',notes:'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Loops_and_iteration',picks:[['HackerRank · Loops','Easy · loops','https://www.hackerrank.com/challenges/js10-loops/problem'],['HackerRank · Try, Catch, and Finally','Easy','https://www.hackerrank.com/challenges/js10-try-catch-and-finally/problem']]},
      {name:'Functions, scope & closures',video:'https://www.youtube.com/@TraversyMedia/playlists',notes:'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Functions',picks:[['HackerRank · Functions','Easy','https://www.hackerrank.com/challenges/js10-function/problem'],['Frontend Mentor · JavaScript projects','Project','https://www.frontendmentor.io/challenges']]},
      {name:'Arrays, objects & strings',video:'https://cs50.harvard.edu/x/2026/weeks/8/',notes:'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array',picks:[['HackerRank · Arrays','Easy','https://www.hackerrank.com/challenges/js10-arrays/problem'],['HackerRank · Objects','Easy','https://www.hackerrank.com/challenges/js10-objects/problem']]},
      {name:'DOM, events, async & fetch',video:'https://cs50.harvard.edu/web/',notes:'https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Scripting',picks:[['MDN · Build a web app','Project','https://developer.mozilla.org/en-US/docs/Learn_web_development/Getting_started/Your_first_website'],['Codewars · JavaScript kata','Practice','https://www.codewars.com/kata/search/javascript']]}
    ]},
    {id:'sql',name:'SQL',icon:'SQL',color:'green',overview:'The language of data queries and a core AI & DS engineering skill.',topics:[
      {name:'SELECT, WHERE & ORDER BY',video:'https://cs50.harvard.edu/x/2026/weeks/7/',notes:'https://www.postgresql.org/docs/current/tutorial-select.html',picks:[['HackerRank · Revising the Select Query I','Easy','https://www.hackerrank.com/challenges/revising-the-select-query/problem'],['SQLBolt · SELECT intro','Warm-up','https://sqlbolt.com/lesson/select_queries_introduction']]},
      {name:'Aggregations & GROUP BY',video:'https://cs50.harvard.edu/x/2026/weeks/7/',notes:'https://www.postgresql.org/docs/current/tutorial-agg.html',picks:[['HackerRank · Average Population','Easy · aggregate','https://www.hackerrank.com/challenges/average-population/problem'],['HackerRank · The Blunder','Easy · aggregate','https://www.hackerrank.com/challenges/the-blunder/problem']]},
      {name:'JOINs & relational thinking',video:'https://cs50.harvard.edu/x/2026/weeks/7/',notes:'https://www.postgresql.org/docs/current/tutorial-join.html',picks:[['HackerRank · Asian Population','Easy · join','https://www.hackerrank.com/challenges/asian-population/problem'],['HackerRank · African Cities','Easy · join','https://www.hackerrank.com/challenges/african-cities/problem']]},
      {name:'Subqueries, CASE & window functions',video:'https://cs50.harvard.edu/x/2026/weeks/7/',notes:'https://www.postgresql.org/docs/current/tutorial-window.html',picks:[['HackerRank · SQL practice track','Guided','https://www.hackerrank.com/domains/sql'],['LeetCode · Database study plan','Guided','https://leetcode.com/studyplan/top-sql-50/']]},
      {name:'Schema, constraints & indexes',video:'https://15445.courses.cs.cmu.edu/fall2025/',notes:'https://www.postgresql.org/docs/current/ddl.html',picks:[['CMU · Database project','Project','https://15445.courses.cs.cmu.edu/fall2025/project1/'],['SQLBolt · Interactive SQL','Guided','https://sqlbolt.com/']]}
    ]}
  ];
  return {topics,years,platforms,collegeLinks,careerYears,directory,hackSources,mitV,mitN,cses,usaco,cfTags,problemPicks,topicSearchTags,langCourses};
})();
